import type { SubscriptionPlan } from "@/types/database";

/**
 * Mirrors supabase/seed.sql so the public pricing section still renders before
 * a database is attached. Live plan rows always win when they exist.
 */
export const STATIC_PLANS: SubscriptionPlan[] = [
  {
    id: "static-free",
    code: "free",
    name_ar: "مجاني",
    name_fr: "Gratuit",
    name_en: "Free",
    description_ar: "ابدأ بمنيو رقمي بسيط ورمز QR واحد.",
    description_fr: "Commencez avec un menu digital simple et un QR code.",
    description_en: "Start with a simple digital menu and one QR code.",
    price_monthly: 0,
    price_yearly: 0,
    currency: "TND",
    max_categories: 5,
    max_products: 30,
    max_tables: 3,
    max_members: 1,
    features: ["menu_digital", "qr_basic", "languages_three", "mobile_menu"],
    is_active: true,
    sort_order: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "static-pro",
    code: "pro",
    name_ar: "برو",
    name_fr: "Pro",
    name_en: "Pro",
    description_ar: "لمطعم أو مقهى يخدم بجدية: منتجات أكثر، طاولات أكثر وإحصائيات.",
    description_fr: "Pour un restaurant ou café actif : plus de produits, plus de tables et des statistiques.",
    description_en: "For a working restaurant or café: more products, more tables and analytics.",
    price_monthly: 29.9,
    price_yearly: 299,
    currency: "TND",
    max_categories: null,
    max_products: 300,
    max_tables: 25,
    max_members: 3,
    features: ["everything_free", "categories_unlimited", "qr_per_table", "analytics", "custom_branding", "product_options"],
    is_active: true,
    sort_order: 2,
    created_at: "",
    updated_at: "",
  },
  {
    id: "static-business",
    code: "business",
    name_ar: "بيزنس",
    name_fr: "Business",
    name_en: "Business",
    description_ar: "لفرق العمل والمشاريع الكبيرة: كل شيء بلا حدود ودعم بالأولوية.",
    description_fr: "Pour les équipes et les grandes enseignes : tout en illimité et support prioritaire.",
    description_en: "For teams and larger venues: everything unlimited plus priority support.",
    price_monthly: 79.9,
    price_yearly: 799,
    currency: "TND",
    max_categories: null,
    max_products: null,
    max_tables: null,
    max_members: 15,
    features: [
      "everything_pro",
      "products_unlimited",
      "tables_unlimited",
      "staff_accounts",
      "advanced_analytics",
      "priority_support",
    ],
    is_active: true,
    sort_order: 3,
    created_at: "",
    updated_at: "",
  },
];
