import type { TemplateRecord } from "@/types/invitation";

/**
 * Static mirror of `supabase/seed.sql`'s templates. Used as a fallback so
 * template browsing and previewing work even before a Supabase project is
 * connected — public catalogue data isn't sensitive, so it's safe to ship a
 * copy here. Keep this in sync with the seed file.
 *
 * Each entry is a complete art direction — palette, type pairing, ornament
 * system, stationery stock and opening choreography — not a color swap.
 */
export const STATIC_TEMPLATES: TemplateRecord[] = [
  {
    id: "static-luxury-gold",
    slug: "luxury-gold",
    name: "Noir & Or",
    nameAr: "نوار وذهب",
    category: "luxury",
    description: "Charcoal black with champagne gold foil, arabesque corners and a wax-sealed envelope.",
    status: "active",
    sortOrder: 1,
    fonts: { heading: "cinzel", body: "cormorant", display: "amiri" },
    theme: {
      background: "#0A0A0B",
      surface: "#17130E",
      primary: "#C9A24A",
      accent: "#EFDDAE",
      text: "#F5ECD8",
      textMuted: "#B9AC90",
      backgroundStyle: "gradient",
      cardRadius: "ornate",
      buttonStyle: "outline-ornate",
      galleryLayout: "grid",
      countdownStyle: "ornate",
      dividerStyle: "ornament",
      motif: "gem",
      openAnimation: "envelope",
      decorativeStyle: "arabesque",
      texture: "velvet",
      frameStyle: "ornate-corner",
      sealColor: "#7C1D2B",
      foil: true,
    },
  },
  {
    id: "static-elegant-white",
    slug: "elegant-white",
    name: "Ivoire & Perle",
    nameAr: "عاج ولؤلؤ",
    category: "classic",
    description: "Ivory and pearl with orchid sprays, an embossed double rule and a folding card.",
    status: "active",
    sortOrder: 2,
    fonts: { heading: "cormorant", body: "cormorant", display: "naskh" },
    theme: {
      background: "#FBF8F3",
      surface: "#FFFFFF",
      primary: "#B99B5F",
      accent: "#E8D9BC",
      text: "#2A2621",
      textMuted: "#857B6C",
      backgroundStyle: "solid",
      cardRadius: "soft",
      buttonStyle: "pill",
      galleryLayout: "minimal",
      countdownStyle: "minimal",
      dividerStyle: "line",
      motif: "sun",
      openAnimation: "paper-fold",
      decorativeStyle: "pearl-bloom",
      texture: "paper",
      frameStyle: "double-rule",
      sealColor: "#D9C6A5",
      foil: true,
    },
  },
  {
    id: "static-floral",
    slug: "floral",
    name: "Olivier & Champagne",
    nameAr: "زيتون وشمبانيا",
    category: "botanical",
    description: "Sage and olive on warm ivory with botanical branches and a quiet light reveal.",
    status: "active",
    sortOrder: 3,
    fonts: { heading: "cormorant", body: "cormorant", display: "naskh" },
    theme: {
      background: "#F4F3EC",
      surface: "#FDFCF8",
      primary: "#7C8A6B",
      accent: "#C9B487",
      text: "#2E332A",
      textMuted: "#77806E",
      backgroundStyle: "solid",
      cardRadius: "soft",
      buttonStyle: "sharp",
      galleryLayout: "romantic",
      countdownStyle: "minimal",
      dividerStyle: "dots",
      motif: "flower",
      openAnimation: "minimal-fade",
      decorativeStyle: "olive-branch",
      texture: "linen",
      frameStyle: "hairline",
      sealColor: "#7C8A6B",
    },
  },
  {
    id: "static-romantic",
    slug: "romantic",
    name: "Bordeaux & Or",
    nameAr: "بوردو وذهب",
    category: "romantic",
    description: "Deep wine and champagne gold with garden roses behind parting satin curtains.",
    status: "active",
    sortOrder: 4,
    fonts: { heading: "cormorant", body: "cormorant", display: "amiri" },
    theme: {
      background: "#2A0E16",
      surface: "#45151F",
      primary: "#C9A24A",
      accent: "#E9C9A0",
      text: "#F7E7DF",
      textMuted: "#C9A69C",
      backgroundStyle: "gradient",
      cardRadius: "round",
      buttonStyle: "pill",
      galleryLayout: "polaroid",
      countdownStyle: "circular",
      dividerStyle: "ornament",
      motif: "sparkle",
      openAnimation: "curtain",
      decorativeStyle: "rose-burgundy",
      texture: "velvet",
      frameStyle: "ornate-corner",
      sealColor: "#E0C089",
      foil: true,
    },
  },
  {
    id: "static-modern",
    slug: "modern",
    name: "Minimal Luxe",
    nameAr: "مينيمال فاخر",
    category: "editorial",
    description: "Warm ivory, taupe and champagne with oversized type and generous negative space.",
    status: "active",
    sortOrder: 5,
    fonts: { heading: "cinzel", body: "cormorant", display: "kufi" },
    theme: {
      background: "#F6F2EC",
      surface: "#FFFDFA",
      primary: "#A08C6E",
      accent: "#D9C7A8",
      text: "#24211D",
      textMuted: "#8A8175",
      backgroundStyle: "solid",
      cardRadius: "none",
      buttonStyle: "sharp",
      galleryLayout: "grid",
      countdownStyle: "minimal",
      dividerStyle: "line",
      motif: "square",
      openAnimation: "minimal-fade",
      texture: "satin",
      frameStyle: "hairline",
      sealColor: "#A08C6E",
      foil: true,
    },
  },
  {
    id: "static-black-gold",
    slug: "black-gold",
    name: "Onyx & Champagne",
    nameAr: "أونيكس وشمبانيا",
    category: "luxury",
    description: "Near-black satin with champagne rules and a single champagne wax seal.",
    status: "active",
    sortOrder: 6,
    fonts: { heading: "cinzel", body: "cormorant", display: "naskh" },
    theme: {
      background: "#050505",
      surface: "#121212",
      primary: "#D8BC7E",
      accent: "#F2E4C1",
      text: "#F6F0E4",
      textMuted: "#A79C88",
      backgroundStyle: "radial",
      cardRadius: "none",
      buttonStyle: "sharp",
      galleryLayout: "masonry",
      countdownStyle: "ornate",
      dividerStyle: "line",
      motif: "moon",
      openAnimation: "wax-seal",
      texture: "satin",
      frameStyle: "double-rule",
      sealColor: "#D8BC7E",
      foil: true,
    },
  },
  {
    id: "static-traditional-arabic",
    slug: "traditional-arabic",
    name: "Royal Arabesque",
    nameAr: "أرابيسك ملكي",
    category: "heritage",
    description: "Midnight navy and gold under an arch, with interlaced geometry and a gold seal.",
    status: "active",
    sortOrder: 7,
    fonts: { heading: "amiri", body: "naskh", display: "amiri" },
    theme: {
      background: "#071A2C",
      surface: "#0E2C46",
      primary: "#CBA95C",
      accent: "#EBD6A0",
      text: "#F4EBD6",
      textMuted: "#A9BACB",
      backgroundStyle: "gradient",
      cardRadius: "ornate",
      buttonStyle: "outline-ornate",
      galleryLayout: "carousel",
      countdownStyle: "ornate",
      dividerStyle: "ornament",
      motif: "wave",
      openAnimation: "wax-seal",
      decorativeStyle: "arabesque",
      texture: "velvet",
      frameStyle: "arch",
      sealColor: "#CBA95C",
      foil: true,
    },
  },
  {
    id: "static-minimal",
    slug: "minimal",
    name: "Blanc Satin",
    nameAr: "أبيض ساتان",
    category: "minimal",
    description: "Pure white satin drawn back from the names, with almost no ornament at all.",
    status: "active",
    sortOrder: 8,
    fonts: { heading: "cormorant", body: "cormorant", display: "naskh" },
    theme: {
      background: "#FFFFFF",
      surface: "#F5F1EA",
      primary: "#9A8C7A",
      accent: "#DED2C0",
      text: "#1F1D1A",
      textMuted: "#8B8378",
      backgroundStyle: "solid",
      cardRadius: "soft",
      buttonStyle: "sharp",
      galleryLayout: "minimal",
      countdownStyle: "minimal",
      dividerStyle: "none",
      motif: "sparkles",
      openAnimation: "curtain",
      texture: "satin",
      sealColor: "#C9BBA6",
    },
  },
];
