import type { TemplateRecord } from "@/types/invitation";

/**
 * Static mirror of `supabase/seed.sql`'s templates. Used as a fallback so
 * template browsing and previewing work even before a Supabase project is
 * connected — public catalogue data isn't sensitive, so it's safe to ship a
 * copy here. Keep this in sync with the seed file.
 */
export const STATIC_TEMPLATES: TemplateRecord[] = [
  {
    id: "static-luxury-gold",
    slug: "luxury-gold",
    name: "Luxury Gold",
    nameAr: "ذهبي فاخر",
    category: "classic",
    description: "Deep charcoal backgrounds with gold foil accents and ornamental Arabic display type.",
    status: "active",
    sortOrder: 1,
    fonts: { heading: "amiri", body: "cairo" },
    theme: {
      background: "#141210",
      surface: "#241f1c",
      primary: "#c9962e",
      accent: "#f0da96",
      text: "#f8edc8",
      textMuted: "#cbc6c0",
      backgroundStyle: "gradient",
      cardRadius: "ornate",
      buttonStyle: "outline-ornate",
      galleryLayout: "grid",
      countdownStyle: "ornate",
      dividerStyle: "ornament",
      motif: "gem",
    },
  },
  {
    id: "static-elegant-white",
    slug: "elegant-white",
    name: "Elegant White",
    nameAr: "أبيض أنيق",
    category: "minimal",
    description: "Soft ivory and cream tones with fine serif type for a clean, timeless look.",
    status: "active",
    sortOrder: 2,
    fonts: { heading: "playfair", body: "inter" },
    theme: {
      background: "#faf7f0",
      surface: "#ffffff",
      primary: "#a97622",
      accent: "#e6c165",
      text: "#241f1c",
      textMuted: "#847970",
      backgroundStyle: "solid",
      cardRadius: "soft",
      buttonStyle: "pill",
      galleryLayout: "minimal",
      countdownStyle: "minimal",
      dividerStyle: "line",
      motif: "sun",
    },
  },
  {
    id: "static-floral",
    slug: "floral",
    name: "Floral",
    nameAr: "زهري",
    category: "romantic",
    description: "Blush pink gradients with a hand-drawn floral motif and italic display type.",
    status: "active",
    sortOrder: 3,
    fonts: { heading: "amiri", body: "cairo" },
    theme: {
      background: "#fbeef0",
      surface: "#f6dfe4",
      primary: "#c85566",
      accent: "#eda3ac",
      text: "#5c2230",
      textMuted: "#a8636f",
      backgroundStyle: "radial",
      cardRadius: "round",
      buttonStyle: "pill",
      galleryLayout: "romantic",
      countdownStyle: "circular",
      dividerStyle: "dots",
      motif: "flower",
    },
  },
  {
    id: "static-romantic",
    slug: "romantic",
    name: "Romantic",
    nameAr: "رومانسي",
    category: "romantic",
    description: "Deep burgundy and rose tones with soft glow accents for an intimate feel.",
    status: "active",
    sortOrder: 4,
    fonts: { heading: "amiri", body: "cairo" },
    theme: {
      background: "#26101a",
      surface: "#3c1620",
      primary: "#e17685",
      accent: "#f6c9cf",
      text: "#fbe4e6",
      textMuted: "#e0aab3",
      backgroundStyle: "gradient",
      cardRadius: "round",
      buttonStyle: "pill",
      galleryLayout: "polaroid",
      countdownStyle: "circular",
      dividerStyle: "ornament",
      motif: "sparkle",
    },
  },
  {
    id: "static-modern",
    slug: "modern",
    name: "Modern",
    nameAr: "عصري",
    category: "contemporary",
    description: "Slate blue-grey with sharp geometric lines and uppercase tracked type.",
    status: "active",
    sortOrder: 5,
    fonts: { heading: "inter", body: "inter" },
    theme: {
      background: "#0a0e12",
      surface: "#1e2833",
      primary: "#8fa7bd",
      accent: "#ffffff",
      text: "#eef2f5",
      textMuted: "#8b98a3",
      backgroundStyle: "solid",
      cardRadius: "none",
      buttonStyle: "sharp",
      galleryLayout: "grid",
      countdownStyle: "minimal",
      dividerStyle: "line",
      motif: "square",
    },
  },
  {
    id: "static-black-gold",
    slug: "black-gold",
    name: "Black & Gold",
    nameAr: "أسود وذهبي",
    category: "prestige",
    description: "Near-black backgrounds with ornate gold detailing for a high-prestige feel.",
    status: "active",
    sortOrder: 6,
    fonts: { heading: "amiri", body: "cairo" },
    theme: {
      background: "#000000",
      surface: "#1c1608",
      primary: "#dcaa42",
      accent: "#f0da96",
      text: "#f8edc8",
      textMuted: "#b8a878",
      backgroundStyle: "radial",
      cardRadius: "ornate",
      buttonStyle: "outline-ornate",
      galleryLayout: "masonry",
      countdownStyle: "ornate",
      dividerStyle: "ornament",
      motif: "moon",
    },
  },
  {
    id: "static-traditional-arabic",
    slug: "traditional-arabic",
    name: "Traditional Arabic",
    nameAr: "تراث عربي",
    category: "heritage",
    description: "Emerald green and gold with arabesque border motifs and Diwani-inspired display type.",
    status: "active",
    sortOrder: 7,
    fonts: { heading: "amiri", body: "cairo" },
    theme: {
      background: "#082420",
      surface: "#155048",
      primary: "#dcaa42",
      accent: "#f0da96",
      text: "#f8edc8",
      textMuted: "#a9c9c0",
      backgroundStyle: "pattern",
      cardRadius: "ornate",
      buttonStyle: "outline-ornate",
      galleryLayout: "carousel",
      countdownStyle: "ornate",
      dividerStyle: "ornament",
      motif: "wave",
    },
  },
  {
    id: "static-minimal",
    slug: "minimal",
    name: "Minimal",
    nameAr: "بسيط ونقي",
    category: "minimalist",
    description: "Pure white and soft grey with generous whitespace and light-weight type.",
    status: "active",
    sortOrder: 8,
    fonts: { heading: "inter", body: "inter" },
    theme: {
      background: "#ffffff",
      surface: "#f7f7f5",
      primary: "#4f463f",
      accent: "#c9962e",
      text: "#241f1c",
      textMuted: "#a89f97",
      backgroundStyle: "solid",
      cardRadius: "soft",
      buttonStyle: "sharp",
      galleryLayout: "minimal",
      countdownStyle: "minimal",
      dividerStyle: "none",
      motif: "sparkles",
    },
  },
];
